"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const categoryController_1 = require("../controllers/categoryController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.post("/category", (0, auth_1.authMiddleware)("admin"), categoryController_1.createCategory);
router.get("/category", categoryController_1.getAllCategory);
router.get("/category/:id", categoryController_1.getCategoryById);
router.patch("/category/:id", (0, auth_1.authMiddleware)("admin"), categoryController_1.updateCategory);
router.delete("/category/:id", categoryController_1.deleteCategory);
exports.default = router;
