"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const orderController_1 = require("../controllers/orderController");
const router = (0, express_1.Router)();
router.post("/order", orderController_1.createOrder);
router.get("/order", orderController_1.getAllOrder);
router.patch("/order/:id", orderController_1.updateOrder);
router.get("/order/:id", orderController_1.getOrderById);
router.delete("/order", orderController_1.deleteOrder);
exports.default = router;
