"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const productController_1 = require("../controllers/productController");
const router = (0, express_1.Router)();
router.post("/product", (0, auth_1.authMiddleware)("admin"), productController_1.createProduct);
router.get("/product", productController_1.getAllProduct);
router.get("/product/:id", productController_1.getProductById);
router.patch("/product/:id", (0, auth_1.authMiddleware)("admin"), productController_1.updateProduct);
router.delete("/product/:id", productController_1.deleteProduct);
exports.default = router;
